@startuml

cloud #LightGrey {
    [Browser] #LightBlue
}

frame Backend #LightGrey {
    [nginx] << HTTP Proxy >> #LightGreen
    [demo-site] << Web server >> #Yellow
    [github-proxy] << REST server >> #Orange
    [dockerhub-proxy] << REST server >> #Orange
    
    [nginx-pygen] << configuration generator >> #Pink
    [certbot-pygen] << configuration generator >> #Pink
    [certbot-helper] << SSL certificate manager >> #c99
}

[Browser] =d=> [nginx] : <b>all</b> <i>https://*.viktoradam.net</i> requests

[nginx] =l=> [demo-site] : <i>demo.</i>viktoradam.net
[nginx] =r=> [github-proxy] : <i>api.</i>viktoradam.net/<i>github</i>
[nginx] =d=> [dockerhub-proxy] : <i>api.</i>viktoradam.net/<i>docker</i>

[nginx-pygen] --u-> [nginx] : Configure routing
[certbot-helper] --u-> [nginx] : Manage SSL certificates
[certbot-pygen] -l-> [certbot-helper] : Configure secure domains

[Browser] ..d.> [demo-site] : HTTP GET / \n -> HTML
[Browser] ..d.> [demo-site] : HTTP POST /render \n JSON -> HTML
[Browser] ..d.> [github-proxy] : HTTP GET * \n -> JSON

@enduml
